
from enum import Enum
INSTRUCTION_START_ADDRESS = 0
DATA_START_ADDRESS = 63
MAIN_MEMORY_SIZE = 96
PC_START_ADD = 0
NUM_REGISTERS = 32
WORD_SIZE_IN_BYTES = 4
NO_OF_SETS_D_CACHE = 2


LW_INSTR = "LW"
SW_INSTR = "LW"


LD_INSTR = "L.D"
SD_INSTR = "S.D"
ADDD_INSTR = "ADD.D"
SUBD_INSTR = "SUB.D"
MULD_INSTR = "MUL.D"
DIVD_INSTR = "DIV.D"
DADD_INSTR = "DADD"
DADDI_INSTR = "DADDI"
DSUB_INSTR = "DSUB"
DSUBI_INSTR = "DSUBI"
AND_INSTR = "AND"
ANDI_INSTR = "ANDI"
OR_INSTR = "OR"
ORI_INSTR = "ORI"

HLT_INSTR = "HLT"

LI_INSTR = "LI"
LUI_INSTR = "LUI"
BEQ_INSTR = "BEQ"
BNE_INSTR = "BNE"
J_INSTR = "J"


class FPType(Enum):

    IntALU = 0
    FPAdder = 1
    FPMul = 2
    FPDiv = 3
    ICache = 4
